apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nlw-passin
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/JacksonFA/nlw-unite-monorepo.git
    targetRevision: HEAD
    path: node/deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: nlw
  syncPolicy:
    automated:
      prune: true
