apiVersion: v1
kind: Secret

metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: git@github.com:JacksonFA/nlw-unite-monorepo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAUhkpeD0cdthKY5uTnF18/nCVx8rNWVjwy53Qpm/jGBwAAAIi+klZxvpJW
    cQAAAAtzc2gtZWQyNTUxOQAAACAUhkpeD0cdthKY5uTnF18/nCVx8rNWVjwy53Qpm/jGBw
    AAAECVpdgWseyP7KRHcWl52VwvlbPKd9SBKxYykSFs4q73OxSGSl4PRx22Epjm5OcXXz+c
    JXHys1ZWPDLndCmb+MYHAAAAAAECAwQF
    -----END OPENSSH PRIVATE KEY-----