name: Node-CI_CD

on:
  push:
    branches:
      - main
    paths:
      - node/**
  workflow_dispatch:

jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t jacksonsfa/passin-node:${{ steps.generate_sha.outputs.sha }} ./node/

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push jacksonsfa/passin-node:${{ steps.generate_sha.outputs.sha }}
        docker tag jacksonsfa/passin-node:${{ steps.generate_sha.outputs.sha }} jacksonsfa/passin-node:latest
        docker push jacksonsfa/passin-node:latest

    - name: Update image tag
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: main
        valueFile: 'node/deploy/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ steps.generate_sha.outputs.sha }}
        commitChange: true
        message: 'new: updated tag in value Helms'
